/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solitto.trabalho;

import java.util.LinkedList;

/**
 *
 * @author aliss_000
 */
public class frmRelVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRelVenda
     */
    public frmRelVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstVendas = new LinkedList<Venda>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRelVenda = new javax.swing.JTextPane();

        lstVendas = org.jdesktop.observablecollections.ObservableCollections.observableList(lstVendas);

        setClosable(true);
        setTitle("Relatório Vendas");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtRelVenda.setEditable(false);
        jScrollPane1.setViewportView(txtRelVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(380, 200, 518, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        for(int i = 0; i < lstVendas.size(); i++)
        {
            txtRelVenda.setText(txtRelVenda.getText() + "Cliente: " + lstVendas.get(i).getC().getNome().toString() + "\n");
            txtRelVenda.setText(txtRelVenda.getText() + "Endereço: " + lstVendas.get(i).getC().getEndereco().toString()+ " nº.:" + lstVendas.get(i).getC().getNum().toString() + "\n");
            
            txtRelVenda.setText(txtRelVenda.getText() + "Itens Venda: \n");
            
            for(int j = 0; j < lstVendas.get(i).itens.size(); j++)
            {
                txtRelVenda.setText(txtRelVenda.getText() + " - Descrição: " + ((Produto)lstVendas.get(i).itens.get(j)).getDescricao().toString() + " Marca: " + ((Produto)lstVendas.get(i).itens.get(j)).getMarca().toString() + "\n");                
            }
            txtRelVenda.setText(txtRelVenda.getText() + "\n\n");
        }
        
        
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public java.util.List<Venda> lstVendas;
    private javax.swing.JTextPane txtRelVenda;
    // End of variables declaration//GEN-END:variables
}
